services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    restart: always
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  db:
    environment:
      POSTGRES_USER: feira
      POSTGRES_PASSWORD_FILE: /run/secrets/db
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 5s
      test: ["CMD", "pg_isready", "-U", "feira"]
      timeout: 1s
    image: postgres
    restart: always
    secrets:
      - db
    volumes:
      - ./db/data:/var/lib/postgresql/data:rw
  rest-api:
    command: "npm start"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 5s
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      timeout: 1s
    image: node
    restart: always
    user: "node"
    volumes:
      - ./rest-api:/home/node/app:ro
    working_dir: /home/node/app
  http-proxy:
    depends_on:
      - mqtt-broker
      - rest-api
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 1s
      test: ["CMD", "curl", "-f", "https://feira-de-jogos.dev.br"]
      timeout: 1s
    image: nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: always
    volumes:
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./frontend:/frontend:ro
      - ./jogos:/jogos:ro
      - ./http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  stun:
    image: coturn/coturn
    network_mode: host
    restart: always
    volumes:
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/fullchain.pem:/etc/fullchain.pem:ro
      - /etc/letsencrypt/live/feira-de-jogos.dev.br/privkey.pem:/etc/privkey.pem:ro
      - ./stun/coturn.conf:/etc/turnserver.conf:ro
secrets:
  db:
    file: secret-db
